-- SpendIQ Demand Intake + TPRM stores (invent-from-scratch domains; seeded from the
-- SpendIQ prototype so the views render live DB data at full fidelity). JSONB payload holds
-- the rich record; a few columns are surfaced for list filtering.
CREATE TABLE IF NOT EXISTS proc.bp_demand (
  demand_id text PRIMARY KEY,
  title text, phase_idx int, status text, requester text, category text,
  value_text text, payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS proc.bp_tprm_supplier (
  tp_id text PRIMARY KEY,
  name text, segment text, criticality text, country text,
  inherent_risk text, residual_risk text, payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO proc.bp_demand (demand_id,title,phase_idx,status,requester,category,value_text,payload) VALUES ('DM-2041',$t$Cloud data platform — 3-yr renewal$t$,1,'In approval',$o$James Walsh$o$,'SaaS / IT','£480,000',$json${"title":"Cloud data platform — 3-yr renewal","profile":"Procurement","cat":"SaaS / IT","party":"Northwind Cloud","value":"£480,000","phaseIdx":1,"status":"In approval","sub":"Pending approver 1…n","owner":"James Walsh","sla":"2 days left","tier":4,"apIdx":1,"problem":{"cur":"Three overlapping data tools across BUs; spend fragmented and partly off-contract.","des":"Single consolidated platform on a 3-year agreement with committed volume discounts.","inaction":"£62k/yr leakage from duplication & off-contract buying."},"criteria":["Consolidate to one platform","≥15% unit-rate reduction","99.95% SLA"],"objective":"FY26 IT cost-optimisation OKR","finance":{"cc":"IT-3300","budget":"Budgeted","struct":"Opex · recurring","tco":"£1.32M / 3yr","saving":"£72,000","type":"Hard / cash","phasing":"£160k · £160k · £160k"},"approvals":[["AI validation","done","Automated · level 0"],["James Walsh","act","Head of Procurement · level 1"],["Finance gate","wait","Budget & policy"],["CFO sign-off","wait","Required > £250k"]],"benefit":{"baseline":"£540k/yr","target":"£468k/yr","forecast":"£470k","realised":"—","owner":"S. Patel (Finance)"},"msgs":[{"who":"James Walsh","init":"JW","clr":"var(--brand)","time":"Mon","text":"Need the should-cost floor before I approve — can sourcing share it?","state":"answered"},{"who":"You","init":"NG","clr":"var(--brand-ink)","time":"Mon","text":"Floor is £445k; benchmark attached.","state":"resolved"}]}$json$) ON CONFLICT (demand_id) DO NOTHING;
INSERT INTO proc.bp_demand (demand_id,title,phase_idx,status,requester,category,value_text,payload) VALUES ('DM-2042',$t$Office supplies framework refresh$t$,0,'Validated',$o$You$o$,'Office & facilities','£36,000',$json${"title":"Office supplies framework refresh","profile":"Procurement","cat":"Office & facilities","party":"Acme Stationers","value":"£36,000","phaseIdx":0,"status":"Validated","sub":"Category assigned","owner":"You","sla":"4 days left","tier":2,"apIdx":0,"finance":{"cc":"FAC-1100","budget":"Budgeted","struct":"Opex · recurring"},"approvals":[["Auto-validate","done","Rules engine"],["Category buyer","act","Pending review"]],"msgs":[]}$json$) ON CONFLICT (demand_id) DO NOTHING;
INSERT INTO proc.bp_demand (demand_id,title,phase_idx,status,requester,category,value_text,payload) VALUES ('DM-2048',$t$Warehouse robotics — capex$t$,3,'PO approved',$o$R. Green$o$,'Operations','£610,000',$json${"title":"Warehouse robotics — capex","profile":"Procurement","cat":"Operations","party":"BlueLine Freight","value":"£610,000","phaseIdx":3,"status":"PO approved","sub":"PO in approval","owner":"R. Green","sla":"On track","tier":3,"apIdx":3,"problem":{"cur":"Manual pick-pack limiting throughput at peak.","des":"Automated robotics line to lift throughput 35%.","inaction":"£140k/yr overtime + missed SLAs."},"criteria":["+35% throughput","Payback < 3 yrs"],"objective":"Operations capacity programme","finance":{"cc":"OPS-5200","budget":"Budgeted","struct":"Capex · one-time","tco":"£780k / 5yr","saving":"£190,000","type":"Cost avoidance","phasing":"£610k · £0 · £0"},"approvals":[["AI validation","done","Automated"],["Ops director","done","Approved"],["Finance","done","Budget confirmed"],["PO desk","act","Issuing PO"]],"msgs":[]}$json$) ON CONFLICT (demand_id) DO NOTHING;
INSERT INTO proc.bp_demand (demand_id,title,phase_idx,status,requester,category,value_text,payload) VALUES ('DM-2050',$t$Logistics rate consolidation$t$,4,'Realising',$o$S. Patel$o$,'Logistics','£233,900',$json${"title":"Logistics rate consolidation","profile":"Procurement","cat":"Logistics","party":"BlueLine Freight","value":"£233,900","phaseIdx":4,"status":"Realising","sub":"Tracking","owner":"S. Patel","sla":"In-year tracking","tier":5,"apIdx":3,"problem":{"cur":"Freight rates above benchmark across lanes.","des":"Consolidated lane rates at contracted floor.","inaction":"£20k/yr above benchmark."},"criteria":["Apply contract rate to all lanes","≥12% rate reduction"],"objective":"Logistics savings programme","finance":{"cc":"LOG-4400","budget":"Budgeted","struct":"Opex · recurring","tco":"£702k / 3yr","saving":"£28,000","type":"Hard / cash","phasing":"£78k · £78k · £78k"},"approvals":[["AI validation","done","Automated"],["Buyer","done","Approved"],["Finance gate","done","Validated"]],"benefit":{"baseline":"£261.9k/yr","target":"£233.9k/yr","forecast":"£236k","realised":"£18k YTD","owner":"S. Patel (Finance)"},"msgs":[{"who":"Sunita Patel","init":"SP","clr":"var(--good)","time":"Tue","text":"Realised £18k so far — on track to target. Finance-validated.","state":"resolved"}]}$json$) ON CONFLICT (demand_id) DO NOTHING;
INSERT INTO proc.bp_demand (demand_id,title,phase_idx,status,requester,category,value_text,payload) VALUES ('DM-2055',$t$Enterprise renewal — Vertex Group$t$,1,'Margin assessed',$o$A. Okafor$o$,'Platform / Enterprise','£420,000',$json${"title":"Enterprise renewal — Vertex Group","profile":"Sales","cat":"Platform / Enterprise","party":"Vertex Group","value":"£420,000","phaseIdx":1,"status":"Margin assessed","sub":"Margin floor tested","owner":"A. Okafor","sla":"3 days left","tier":6,"apIdx":1,"problem":{"cur":"Customer on legacy pricing; competitor circling at renewal.","des":"Multi-year renewal with uplift, protecting margin above floor.","inaction":"Churn risk on £420k ACV."},"criteria":["Renew ≥ 2 years","Gross margin ≥ 62%","Discount ≤ 8%"],"objective":"FY26 net-revenue-retention target","finance":{"cc":"SAL-2100","budget":"Quota-bearing","struct":"Revenue · recurring","tco":"£1.6M CLV","saving":"64% gross margin","type":"Margin uplift","phasing":"£420k · £441k · £463k"},"approvals":[["Qualification","done","Auto-qualified"],["Deal desk","act","Reviewing discount"],["Pricing approval","wait","VP Sales · > 8% discount"]],"benefit":{"baseline":"58% margin","target":"62% margin","forecast":"64% margin","realised":"—","owner":"Finance (rev rec)"},"msgs":[{"who":"Ada Okafor","init":"AO","clr":"var(--brand)","time":"Wed","text":"Customer pushing for 10% discount — need deal-desk view on the margin floor.","state":"open"}]}$json$) ON CONFLICT (demand_id) DO NOTHING;
INSERT INTO proc.bp_tprm_supplier (tp_id,name,segment,criticality,country,inherent_risk,residual_risk,payload) VALUES ('NWC',$n$Northwind Cloud$n$,'Strategic','Material outsourcing','US','crit','high',$json${"id":"NWC","name":"Northwind Cloud","seg":"Strategic","crit":"Material outsourcing","svc":"Core banking SaaS · hosting","country":"US","spend":"£2.4M","inh":"crit","res":"high","trend":"up","dd":"Overdue","next":"Overdue 12d","dom":{"Financial":2,"Cyber & infosec":4,"Compliance & reg":3,"Operational resilience":4,"Concentration":5,"Data privacy":3,"ESG & conduct":2,"Fourth-party":4},"ibs":"Payments processing","tol":"2 hours","exit":"Partial plan","exitT":"9 months","sub":"Limited","cyber":"720","fin":"BBB · stable","media":"2 flags","sanctions":"Clear","certs":"SOC 2 II · ISO 27001","fourth":[["Equinix","Data-centre colocation","US / EU"],["Cloudflare","Edge / DDoS","Global"],["Okta","Identity & access","US"]],"findings":[["high","Concentration — supports 3 critical services","High","CISO","30 Jun"],["med","Exit plan not stress-tested","Medium","COO","15 Jul"],["med","Subcontractor (Okta) DPA pending","Medium","DPO","08 Jul"]],"owner":"A. Mensah · Head of Technology Sourcing","sponsor":"CTO"}$json$) ON CONFLICT (tp_id) DO NOTHING;
INSERT INTO proc.bp_tprm_supplier (tp_id,name,segment,criticality,country,inherent_risk,residual_risk,payload) VALUES ('NXS',$n$Nexus IT Services$n$,'Important','Critical function','IN','high','med',$json${"id":"NXS","name":"Nexus IT Services","seg":"Important","crit":"Critical function","svc":"End-user computing · service desk","country":"IN","spend":"£0.9M","inh":"high","res":"med","trend":"down","dd":"Current","next":"02 Sep 2026","dom":{"Financial":3,"Cyber & infosec":3,"Compliance & reg":3,"Operational resilience":3,"Concentration":3,"Data privacy":4,"ESG & conduct":3,"Fourth-party":3},"ibs":"Colleague IT","tol":"4 hours","exit":"Documented","exitT":"6 months","sub":"Moderate","cyber":"705","fin":"BBB- · stable","media":"Clear","sanctions":"Clear","certs":"ISO 27001","fourth":[["Subco Talent","Offshore staffing","IN"]],"findings":[["med","Offshore data-transfer (SCCs) review","Medium","DPO","12 Jul"],["med","Duplicate-invoice control gap","Medium","AP","05 Jul"]],"owner":"A. Mensah · Technology Sourcing","sponsor":"CIO"}$json$) ON CONFLICT (tp_id) DO NOTHING;
INSERT INTO proc.bp_tprm_supplier (tp_id,name,segment,criticality,country,inherent_risk,residual_risk,payload) VALUES ('BLF',$n$BlueLine Freight & Logistics$n$,'Important','Important','UK','med','med',$json${"id":"BLF","name":"BlueLine Freight & Logistics","seg":"Important","crit":"Important","svc":"Cash-in-transit · logistics","country":"UK","spend":"£0.6M","inh":"med","res":"med","trend":"flat","dd":"Current","next":"14 Nov 2026","dom":{"Financial":3,"Cyber & infosec":2,"Compliance & reg":2,"Operational resilience":3,"Concentration":2,"Data privacy":2,"ESG & conduct":3,"Fourth-party":2},"ibs":"Cash services","tol":"1 day","exit":"Documented","exitT":"3 months","sub":"Good","cyber":"690","fin":"BB · stable","media":"Clear","sanctions":"Clear","certs":"ISO 9001","fourth":[["RegionalCarriers Ltd","Last-mile delivery","UK"]],"findings":[["med","Insurance certificate renewal due","Medium","Vendor mgr","20 Jul"]],"owner":"R. Okafor · Operations Sourcing","sponsor":"COO"}$json$) ON CONFLICT (tp_id) DO NOTHING;
INSERT INTO proc.bp_tprm_supplier (tp_id,name,segment,criticality,country,inherent_risk,residual_risk,payload) VALUES ('PXC',$n$Pixel & Co.$n$,'Tail','Non-critical','UK','low','med',$json${"id":"PXC","name":"Pixel & Co.","seg":"Tail","crit":"Non-critical","svc":"Marketing agency","country":"UK","spend":"£0.27M","inh":"low","res":"med","trend":"up","dd":"Due","next":"Due 9d","dom":{"Financial":4,"Cyber & infosec":2,"Compliance & reg":2,"Operational resilience":1,"Concentration":1,"Data privacy":3,"ESG & conduct":2,"Fourth-party":1},"ibs":"—","tol":"—","exit":"Easy","exitT":"1 month","sub":"High","cyber":"610","fin":"B · negative watch","media":"1 flag","sanctions":"Clear","certs":"—","fourth":[],"findings":[["med","Financial viability — negative outlook","Medium","Finance","30 Jun"],["low","No competing quote on last renewal","Low","Procurement","—"]],"owner":"J. Patel · Senior Manager · Marketing","sponsor":"CMO"}$json$) ON CONFLICT (tp_id) DO NOTHING;
INSERT INTO proc.bp_tprm_supplier (tp_id,name,segment,criticality,country,inherent_risk,residual_risk,payload) VALUES ('LAT',$n$Lattice Advisory$n$,'Strategic','Important','UK','med','low',$json${"id":"LAT","name":"Lattice Advisory","seg":"Strategic","crit":"Important","svc":"Risk & regulatory consulting","country":"UK","spend":"£1.2M","inh":"med","res":"low","trend":"flat","dd":"Current","next":"21 Jan 2027","dom":{"Financial":2,"Cyber & infosec":2,"Compliance & reg":2,"Operational resilience":2,"Concentration":2,"Data privacy":2,"ESG & conduct":1,"Fourth-party":1},"ibs":"—","tol":"—","exit":"Documented","exitT":"2 months","sub":"High","cyber":"760","fin":"A · stable","media":"Clear","sanctions":"Clear","certs":"ISO 27001 · SOC 2 II","fourth":[],"findings":[],"owner":"S. Bauer · Professional Services","sponsor":"CRO"}$json$) ON CONFLICT (tp_id) DO NOTHING;
INSERT INTO proc.bp_tprm_supplier (tp_id,name,segment,criticality,country,inherent_risk,residual_risk,payload) VALUES ('ACS',$n$Acme Stationers$n$,'Tail','Non-critical','UK','low','low',$json${"id":"ACS","name":"Acme Stationers","seg":"Tail","crit":"Non-critical","svc":"Office supplies","country":"UK","spend":"£0.29M","inh":"low","res":"low","trend":"flat","dd":"Current","next":"30 Mar 2027","dom":{"Financial":2,"Cyber & infosec":1,"Compliance & reg":1,"Operational resilience":1,"Concentration":1,"Data privacy":1,"ESG & conduct":2,"Fourth-party":1},"ibs":"—","tol":"—","exit":"Easy","exitT":"1 week","sub":"High","cyber":"—","fin":"BBB","media":"Clear","sanctions":"Clear","certs":"—","fourth":[],"findings":[],"owner":"Procurement ops","sponsor":"—"}$json$) ON CONFLICT (tp_id) DO NOTHING;
